### ISSUE TITLE
Provider install path / documentation

### ISSUE THREAD

**Issue by danekantner** [JupiterOne/terraform-provider-jupiterone#10]
In the documentation -- we haven't been able to get the provider to run from the precise location used in the make install which is~/.terraform.d/plugins/terraform-provider-jupiterone as the actual binary location, and instead use a structure .terraform.d/plugins/foo.com/foo/jupiterone/1.0.1/darwin_amd64/terraform-provider-jupiterone (mac) .terraform.d/plugins/foo.com/foo/jupiterone/1.0.1/linux_amd64/terraform-provider-jupiterone (linux) [as documented](https://www.terraform.io/docs/language/providers/requirements.html#in-house-providers) by Hashi.  

The matching provider block for that example to match is (version is optional in the provider call itself, but not in the actual folder it is stored in):

```
terraform {
  required_providers {
    jupiterone = {
      source  = "foo.com/foo/jupiterone"
      version = "1.0.1"
    }
  }
  required_version = ">= 0.15"
}
```

**Comment by kenanwarren** [comment]
Hey @danekantner, we're actually in the process of migrating the terraform provider to the newest SDK and getting it published to the registry to make using it easier. My guess is in one of the more recent terraform versions they moved the location of the plugins from what we originally expected. I'll be sure to update the install paths as part of the SDK updates but definitely hoping that publishing it to the registry makes it straightforward.

**Comment by kenanwarren** [comment]
Hey @danekantner we published to provider to the terraform registry. The usage is documented below (also in repo).

https://registry.terraform.io/providers/JupiterOne/jupiterone/latest
This should make using the provider a lot easier:
```
terraform {
  required_providers {
    jupiterone = {
      source  = "jupiterone/jupiterone"
      version = "~> 0.2.0"
    }
  }
}

provider "jupiterone" {
  api_key    = "some-key"
  account_id = "some-account"
  region     = "some-region" # optional
}
```

If you have any other ideas for resources you'd like to see in the provider feel free to open an issue for it!
