### ISSUE TITLE
Feature Request: Include Tags in Rule Creation

### ISSUE THREAD

**Issue by fergus-ikigai** [JupiterOne/terraform-provider-jupiterone#88]
Inside the J1 UI, when I go to view a rule, I see an option to create Tags. In the Advanced json view, I can also see tags, like this:
```
  "tags": [
    "AwsConfig"
  ]
```
This option is not available in the `jupiterone_rule` . Could this be added please? It's a very useful option.

**Comment by zemberdotnet** [comment]
Hi @fergus-ikigai  👋 

This feature has been added in `v0.3.0` of `terraform-provider-jupiterone`. See [here](https://github.com/JupiterOne/terraform-provider-jupiterone/blob/main/docs/resources/rule.md#example-usage) for an example.

**Comment by fergus-ikigai** [comment]
Awesome will check out today and get back.
